"""Adding patner and status columns to the user

Revision ID: 27bbd998fdf9
Revises: 9a28159c39e1
Create Date: 2018-01-10 02:08:48.119828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bbd998fdf9'
down_revision = '9a28159c39e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patner', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'patner')
    # ### end Alembic commands ###
