"""second migration

Revision ID: 59399ae855c4
Revises: 1dd8f3a9f4fa
Create Date: 2018-01-09 07:48:27.167894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59399ae855c4'
down_revision = '1dd8f3a9f4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_available')
    # ### end Alembic commands ###
