"""add a new column in proposal

Revision ID: 676bbdb065b8
Revises: ec01d5188d2d
Create Date: 2018-01-11 08:02:36.934262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676bbdb065b8'
down_revision = 'ec01d5188d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('sender_', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'sender_')
    # ### end Alembic commands ###
