"""add an is seen column and a class method to manipulate the same to the proposals model

Revision ID: 7028db341f56
Revises: e46f3a4cdfcd
Create Date: 2018-01-11 23:51:30.629999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7028db341f56'
down_revision = 'e46f3a4cdfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('is_seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'is_seen')
    # ### end Alembic commands ###
