"""add a foreign key user_id to messages model

Revision ID: 92576013b088
Revises: c7559e0333a5
Create Date: 2018-01-10 23:48:50.224117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92576013b088'
down_revision = 'c7559e0333a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'recipient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
