""" create a new model message

Revision ID: c7559e0333a5
Revises: 84265e2f333e
Create Date: 2018-01-10 10:54:31.470216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7559e0333a5'
down_revision = '84265e2f333e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('messages', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('messages')
    # ### end Alembic commands ###
