"""add a new column in proposal

Revision ID: d3a581644a4d
Revises: 676bbdb065b8
Create Date: 2018-01-11 08:03:52.623351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a581644a4d'
down_revision = '676bbdb065b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('sender', sa.String(length=255), nullable=True))
    op.drop_column('proposals', 'sender_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('sender_', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('proposals', 'sender')
    # ### end Alembic commands ###
