"""update the proposal column

Revision ID: ec01d5188d2d
Revises: b6e019e44134
Create Date: 2018-01-11 06:22:21.398550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec01d5188d2d'
down_revision = 'b6e019e44134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('message', sa.String(length=255), nullable=True))
    op.add_column('proposals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('proposals_proposing_fkey', 'proposals', type_='foreignkey')
    op.create_foreign_key(None, 'proposals', 'users', ['user_id'], ['id'])
    op.drop_column('proposals', 'proposing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('proposing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.create_foreign_key('proposals_proposing_fkey', 'proposals', 'users', ['proposing'], ['id'])
    op.drop_column('proposals', 'user_id')
    op.drop_column('proposals', 'message')
    # ### end Alembic commands ###
